### ISSUE TITLE
Error in Check_and_Run.R

### ISSUE THREAD

**Issue by huanghe0220** [TesiNicco/snpXplorer#2]
Hi, @TesiNicco 
I succeeded in installing the packages("data.table", "shiny", "shinyShortcut", "stringr", "ggplot2") in R. But when I run 

> Rscript bin/.shiny_run/shinyShortcut.r

I got this error:

> Listening on http://127.0.0.1:4443
> Error in utils::browseURL(appUrl) :
>   'browser' must be a non-empty character string
> Calls: <Anonymous> -> <Anonymous>
> Execution halted

Do you know why and how can I solve this problem?
Looking forward to your reply!
Thanks.
He Huang

**Comment by TesiNicco** [comment]
Dear He Huang,

Thank you so much for your interest in snpXplorer. 

We note that the web-server version (available at snpxplorer.net is highly recommended). In fact, snpXplorer was born as a standalone tool, but then we realized that it would be much easier for the user to focus on the development of a web-server version. 

So I have to apologize if the instructions in the GitHub page (for the standalone version) are not up-to-date. However, I am happy to assist you during installation. :)

With respect to your error, it may still be a package-problem. In the published manuscript we report that to run, snpXplorer requires R (v3.5+) and python (v3+) correctly installed and accessible in your system. snpXplorer uses the following R packages: shiny, data.table, stringr, ggplot2, liftOver, colourpicker, rvest, plotrix, parallel, SNPlocs.Hsapiens.dfSNP144.GRCh37, lme4, ggsci, RColorBrewer, gprofiler2, GOSemSim, GO.db, org.Hs.eg.db, pheatmap, circlize, devtools, treemap, basicPlotteR, gwascat, GenomicRanges, rtracklayer, Homo.sapiens, BiocGenerics and the following python libraries: re, werkzeug, robobrowser, pygosemsim, numpy, csv, networkx and sys.

I would therefore suggest you to first install all required packages. Do you have any prior experience with shiny applications?

Please do not hesitate to come back to me
We wish you a pleasant day
snpXplorer Team

**Comment by TesiNicco** [comment]
Dear He Huang,

Thank you so much for your interest in snpXplorer. 

We note that the web-server version (available at snpxplorer.net is highly recommended). In fact, snpXplorer was born as a standalone tool, but then we realized that it would be much easier for the user to focus on the development of a web-server version. 

So I have to apologize if the instructions in the GitHub page (for the standalone version) are not up-to-date. However, I am happy to assist you during installation. :)

With respect to your error, it may still be a package-problem. In the published manuscript we report that to run, snpXplorer requires R (v3.5+) and python (v3+) correctly installed and accessible in your system. snpXplorer uses the following R packages: shiny, data.table, stringr, ggplot2, liftOver, colourpicker, rvest, plotrix, parallel, SNPlocs.Hsapiens.dfSNP144.GRCh37, lme4, ggsci, RColorBrewer, gprofiler2, GOSemSim, GO.db, org.Hs.eg.db, pheatmap, circlize, devtools, treemap, basicPlotteR, gwascat, GenomicRanges, rtracklayer, Homo.sapiens, BiocGenerics and the following python libraries: re, werkzeug, robobrowser, pygosemsim, numpy, csv, networkx and sys.

I would therefore suggest you to first install all required packages. Do you have any prior experience with shiny applications?

Please do not hesitate to come back to me
We wish you a pleasant day
snpXplorer Team

**Comment by huanghe0220** [comment]
Hi, @TesiNicco ,thanks for your reply.
Unfortunately, since I don't have any prior experience with shiny applications, I got a problem of starting shiny sever from the remote server with my local machine

> * Writing .shiny_run/shinyShortcut.r 

> * Writing shinyShortcut.desktop 

> Loading required package: shiny  

> Listening on http://127.0.0.1:7431 

> xdg-open: no method available for opening 'http://127.0.0.1:7431'

Do you have any ideas?
I would appreciate your immediate attention to this matter.
Best wishes,
He Huang

**Comment by TesiNicco** [comment]
Dear He,

I have experienced a similar problem in the past while running a shiny application on a remote server (based on CentOS). In my case, there was no solution but to change server. I did not find problems with running shiny on macOS and Ubuntu.
 
However, this really depends on the server you are using, so you may want to ask more information to your system administrator.

In general, shiny outputs on a local address (in your case I see http://127.0.0.1, port 7431). It seems that there is a problem with the address or the port. Note that address and port can be changed.
 
I would suggest you to try to run a simple shiny application on your laptop and also on the remote server. You can find a simple shiny app here —> https://shiny.rstudio.com/articles/basics.html <https://shiny.rstudio.com/articles/basics.html> . At the same link you can also find some basic information about the structure of shiny applications.

Please do not hesitate to reach us back for further assistance
Best,
snpXplorer Team

**Comment by huanghe0220** [comment]
Thanks for your reply! I guess I would use the web-server for convenience, for it'll be a big trouble to change server. I will try to run a simple shiny app to gain more experience. Thank you once again for your support!

All the best,
He Huang
